server {
    server_name sniffly.musicsian.com;
    root  /var/www/sniffly.musicsian.com/current;
    index index.html;

    access_log /var/log/nginx/sniffly.access.log;
    error_log  /var/log/nginx/sniffly.error.log;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Cache static assets
    location /assets/ {
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Cache release files but allow revalidation
    location /releases/ {
        expires 7d;
        add_header Cache-Control "public, must-revalidate";
        # Force download of .dmg files
        if ($request_uri ~* \.dmg$) {
            add_header Content-Disposition 'attachment';
        }
    }

    listen 80;
}
